
services:
  replica_db:
    image: mysql:latest
    container_name: infralogDbReplica
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - replica-data:/var/lib/mysql
    command:
      --server-id=2
      --read-only=1
      --relay-log=mysql-relay-bin
      --gtid_mode=ON
      --enforce-gtid-consistency=ON
      --log-slave-updates=ON
      --binlog-format=ROW
      --sync-binlog=1

volumes:
  replica-data:
