services:
  db:
    image: mysql:latest
    container_name: infralogDbContainer01
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Fox77Fire**
      - MYSQL_DATABASE=infralogDb01
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - /home/db1-user/infralog/infralog_data:/var/lib/mysql
  volumes:
    infralog_data
