services:
  db:
    image: mysql:latest
    container_name: infralogDbContainer01
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Fox77Fire**
      - MYSQL_DATABASE=infralogDb01
    volumes:
      - /home/db1-user/infralog/db:/var/lib/mysql
