services:
  primary_db:
    image: mysql:latest
    container_name: "infralogDbPrim"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./infralog_data:/var/lib/mysql

    command:
      --server-id=1
      --log-bin=mysql-bin
      --bind-address=0.0.0.0
      --binlog-do-db=infralogDb01
      --default-authentication-plugin=mysql_native_password

volumes:
  primary_data:
