services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
      - ./logs:/vault/logs
      - ./certs:/vault/certs:z
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200
#      - VAULT_API_ADDR=https://127.0.0.1:8200
      - VAULT_CACERT=/vault/certs/ca.pem
    command: "vault server -config=/vault/config/vault-config.hcl"
